package Formulario;
import javax.swing.JFrame;
public class frm_Menu extends javax.swing.JFrame {

    /**
     * Creates new form frm_Menu
     */
    public frm_Menu() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMiAlmacen = new javax.swing.JMenuItem();
        jMiMarca = new javax.swing.JMenuItem();
        jMiPresentacion = new javax.swing.JMenuItem();
        jMiArticulo = new javax.swing.JMenuItem();
        jMiCliente = new javax.swing.JMenuItem();
        jMiLocal = new javax.swing.JMenuItem();
        jMiProveedor = new javax.swing.JMenuItem();
        jMiTipoManoObra = new javax.swing.JMenuItem();
        jMiVehiculoClase = new javax.swing.JMenuItem();
        jMiVehiculoMarca = new javax.swing.JMenuItem();
        jMiModelo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpEscritorio.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1074, Short.MAX_VALUE)
        );
        dpEscritorioLayout.setVerticalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));

        jMenu1.setBackground(new java.awt.Color(0, 102, 255));
        jMenu1.setText("MANTENIMIENTO");

        jMiAlmacen.setText("Almacen");
        jMiAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiAlmacenActionPerformed(evt);
            }
        });
        jMenu1.add(jMiAlmacen);

        jMiMarca.setText("Marca");
        jMiMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiMarcaActionPerformed(evt);
            }
        });
        jMenu1.add(jMiMarca);

        jMiPresentacion.setText("Presentación");
        jMiPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiPresentacionActionPerformed(evt);
            }
        });
        jMenu1.add(jMiPresentacion);

        jMiArticulo.setText("Artículo");
        jMiArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiArticuloActionPerformed(evt);
            }
        });
        jMenu1.add(jMiArticulo);

        jMiCliente.setText("Cliente");
        jMiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMiCliente);

        jMiLocal.setText("Local");
        jMiLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiLocalActionPerformed(evt);
            }
        });
        jMenu1.add(jMiLocal);

        jMiProveedor.setText("Proveedor");
        jMiProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiProveedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMiProveedor);

        jMiTipoManoObra.setText("Tipo Mano Obra");
        jMiTipoManoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiTipoManoObraActionPerformed(evt);
            }
        });
        jMenu1.add(jMiTipoManoObra);

        jMiVehiculoClase.setText("Vehículo Clase");
        jMiVehiculoClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiVehiculoClaseActionPerformed(evt);
            }
        });
        jMenu1.add(jMiVehiculoClase);

        jMiVehiculoMarca.setText("Vehículo Marca");
        jMiVehiculoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiVehiculoMarcaActionPerformed(evt);
            }
        });
        jMenu1.add(jMiVehiculoMarca);

        jMiModelo.setText("Vehículo Modelo");
        jMiModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiModeloActionPerformed(evt);
            }
        });
        jMenu1.add(jMiModelo);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 153, 255));
        jMenu2.setText("TRANSACCIONES");

        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("CONSULTAS");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("REPORTES");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMiMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiMarcaActionPerformed
       this.limpiarEscritorio(); 
       frm_Almac_Marca jif =  new frm_Almac_Marca(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiMarcaActionPerformed

    private void jMiAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiAlmacenActionPerformed
       this.limpiarEscritorio(); 
       frm_Almac_Almacen jif =  new frm_Almac_Almacen(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiAlmacenActionPerformed

    private void jMiPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiPresentacionActionPerformed
       this.limpiarEscritorio(); 
       frm_Almac_Presentacion jif =  new frm_Almac_Presentacion(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiPresentacionActionPerformed

    private void jMiArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiArticuloActionPerformed
       this.limpiarEscritorio(); 
       frm_Almac_Tipo_Articulo jif =  new frm_Almac_Tipo_Articulo(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiArticuloActionPerformed

    private void jMiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiClienteActionPerformed
       this.limpiarEscritorio(); 
       frm_Confi_Cliente jif =  new frm_Confi_Cliente(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiClienteActionPerformed

    private void jMiLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiLocalActionPerformed
       this.limpiarEscritorio(); 
       frm_Confi_local jif =  new frm_Confi_local(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiLocalActionPerformed

    private void jMiProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiProveedorActionPerformed
       this.limpiarEscritorio(); 
       frm_Confi_Proveedor jif =  new frm_Confi_Proveedor(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiProveedorActionPerformed

    private void jMiTipoManoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiTipoManoObraActionPerformed
       this.limpiarEscritorio(); 
       frm_Confi_Tipo_Mano_Obra jif =  new frm_Confi_Tipo_Mano_Obra(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiTipoManoObraActionPerformed

    private void jMiVehiculoClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiVehiculoClaseActionPerformed
       this.limpiarEscritorio(); 
       frm_Confi_Vehiculo_Clase jif =  new frm_Confi_Vehiculo_Clase(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiVehiculoClaseActionPerformed

    private void jMiVehiculoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiVehiculoMarcaActionPerformed
       this.limpiarEscritorio(); 
       frm_Confi_Vehiculo_Marca jif =  new frm_Confi_Vehiculo_Marca(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiVehiculoMarcaActionPerformed

    private void jMiModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiModeloActionPerformed
       this.limpiarEscritorio(); 
       frm_Confi_Vehiculo_Modelo jif =  new frm_Confi_Vehiculo_Modelo(); //crear un nuevo objeto en la pantalla, instanciar este objeto
       this.dpEscritorio.add(jif);
       jif.setVisible(true);
    }//GEN-LAST:event_jMiModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMiAlmacen;
    private javax.swing.JMenuItem jMiArticulo;
    private javax.swing.JMenuItem jMiCliente;
    private javax.swing.JMenuItem jMiLocal;
    private javax.swing.JMenuItem jMiMarca;
    private javax.swing.JMenuItem jMiModelo;
    private javax.swing.JMenuItem jMiPresentacion;
    private javax.swing.JMenuItem jMiProveedor;
    private javax.swing.JMenuItem jMiTipoManoObra;
    private javax.swing.JMenuItem jMiVehiculoClase;
    private javax.swing.JMenuItem jMiVehiculoMarca;
    // End of variables declaration//GEN-END:variables
    private void limpiarEscritorio() 
    {
       this.dpEscritorio.removeAll(); //primero el remove
       this.dpEscritorio.repaint(); //segundo repaint pera pintar un nuevo
    }
}
