
package Formulario;

import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author PC
 */
public class frm_Menu extends javax.swing.JFrame {

    /**
     * Creates new form frm_Menu
     */
    public frm_Menu() {
        initComponents();
        
        this.setLocation(0, 0);
        
        this.txtid_usuario.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdp_escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmi_cliente = new javax.swing.JMenuItem();
        jmi_proveedor = new javax.swing.JMenuItem();
        jmi_usuario = new javax.swing.JMenuItem();
        jmi_personal = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmi_articulo = new javax.swing.JMenuItem();
        jminueva_compra = new javax.swing.JMenuItem();
        jmiregistro_compra = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jminueva_venta = new javax.swing.JMenuItem();
        jmiregistro_venta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jdp_escritorio.setBackground(new java.awt.Color(255, 255, 255));

        txtid_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_usuarioActionPerformed(evt);
            }
        });

        jdp_escritorio.setLayer(txtid_usuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp_escritorioLayout = new javax.swing.GroupLayout(jdp_escritorio);
        jdp_escritorio.setLayout(jdp_escritorioLayout);
        jdp_escritorioLayout.setHorizontalGroup(
            jdp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtid_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1326, Short.MAX_VALUE))
        );
        jdp_escritorioLayout.setVerticalGroup(
            jdp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_escritorioLayout.createSequentialGroup()
                .addContainerGap(670, Short.MAX_VALUE)
                .addComponent(txtid_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(33, 150, 243));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(420, 42));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/dashboard.png"))); // NOI18N
        jMenu1.setText("Dashboard");
        jMenu1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton-de-configuracion-negro_1.png"))); // NOI18N
        jMenu2.setText("Configuración");
        jMenu2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jmi_cliente.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jmi_cliente.setText("Cliente");
        jmi_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_clienteActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_cliente);

        jmi_proveedor.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jmi_proveedor.setText("Proveedor");
        jmi_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_proveedorActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_proveedor);

        jmi_usuario.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jmi_usuario.setText("Usuario");
        jmi_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_usuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_usuario);

        jmi_personal.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jmi_personal.setText("Personal");
        jmi_personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_personalActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_personal);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/caja_1.png"))); // NOI18N
        jMenu3.setText("Almacen");
        jMenu3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jmi_articulo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jmi_articulo.setText("Artículo");
        jmi_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_articuloActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_articulo);

        jminueva_compra.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jminueva_compra.setText("Nueva compra");
        jminueva_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jminueva_compraActionPerformed(evt);
            }
        });
        jMenu3.add(jminueva_compra);

        jmiregistro_compra.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jmiregistro_compra.setText("Registros de compras");
        jmiregistro_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiregistro_compraActionPerformed(evt);
            }
        });
        jMenu3.add(jmiregistro_compra);

        jMenuBar1.add(jMenu3);

        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/facturas-de-papel.png"))); // NOI18N
        jMenu5.setText("Venta");
        jMenu5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jminueva_venta.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jminueva_venta.setText("Nueva venta");
        jminueva_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jminueva_ventaActionPerformed(evt);
            }
        });
        jMenu5.add(jminueva_venta);

        jmiregistro_venta.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jmiregistro_venta.setText("Registros de ventas");
        jmiregistro_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiregistro_ventaActionPerformed(evt);
            }
        });
        jMenu5.add(jmiregistro_venta);

        jMenuBar1.add(jMenu5);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton-de-encendido-apagado_1.png"))); // NOI18N
        jMenu4.setText("Salir");
        jMenu4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jMenuItem1.setBackground(new java.awt.Color(33, 150, 243));
        jMenuItem1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp_escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp_escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmi_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_clienteActionPerformed
        // TODO add your handling code here:
        frm_Confi_Cliente f_cliente = new frm_Confi_Cliente();
        f_cliente.setVisible(true);
         
        
    }//GEN-LAST:event_jmi_clienteActionPerformed

    private void jmi_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_usuarioActionPerformed
        // TODO add your handling code here:
        
	frm_Confi_Usuario form = new frm_Confi_Usuario();
        form.setVisible(true);
        
    }//GEN-LAST:event_jmi_usuarioActionPerformed

    private void jmi_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_proveedorActionPerformed
        // TODO add your handling code here:
        frm_Confi_Proveedor form = new frm_Confi_Proveedor();
        form.setVisible(true);
        
    }//GEN-LAST:event_jmi_proveedorActionPerformed

    private void jmi_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_personalActionPerformed
        // TODO add your handling code here:
        frm_Confi_Personal form = new frm_Confi_Personal();
        form.setVisible(true);
        
    }//GEN-LAST:event_jmi_personalActionPerformed

    private void jmi_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_articuloActionPerformed
        // TODO add your handling code here:
        frm_Almac_Articulo form = new frm_Almac_Articulo();
        form.setVisible(true);
        
    }//GEN-LAST:event_jmi_articuloActionPerformed

    private void jminueva_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jminueva_ventaActionPerformed
        // TODO add your handling code here:
        
        frm_Nueva_Venta form = new frm_Nueva_Venta(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_jminueva_ventaActionPerformed

    private void jminueva_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jminueva_compraActionPerformed
        // TODO add your handling code here:
        frm_Nueva_Compra form = new frm_Nueva_Compra(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_jminueva_compraActionPerformed

    private void jmiregistro_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiregistro_compraActionPerformed
        // TODO add your handling code here:
        frm_Almac_Compra form = new frm_Almac_Compra(this, true);
        form.setVisible(true);
        
    }//GEN-LAST:event_jmiregistro_compraActionPerformed

    private void jmiregistro_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiregistro_ventaActionPerformed
        // TODO add your handling code here:
        frm_Venta_Venta form = new frm_Venta_Venta(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_jmiregistro_ventaActionPerformed

    private void txtid_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
       
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
         

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdp_escritorio;
    private javax.swing.JMenuItem jmi_articulo;
    private javax.swing.JMenuItem jmi_cliente;
    private javax.swing.JMenuItem jmi_personal;
    private javax.swing.JMenuItem jmi_proveedor;
    private javax.swing.JMenuItem jmi_usuario;
    private javax.swing.JMenuItem jminueva_compra;
    private javax.swing.JMenuItem jminueva_venta;
    private javax.swing.JMenuItem jmiregistro_compra;
    private javax.swing.JMenuItem jmiregistro_venta;
    public static final javax.swing.JTextField txtid_usuario = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
